### PR TITLE
Proper password

### PR DESCRIPTION
**Pull request by szepeviktor**
Even seeing "password" as password in one-time run CI is frightening!

### CODE REVIEW

**Comment by dingo-d** [comment]
I'll probably remove this altogether as the running time of tests on GH actions this way is too slow. Plus this is not sensitive information in any way so it's ok 🙂

**Comment by szepeviktor** [comment]
I've meant to refrain from making people think that in certain circumstances `password` could be used as a password.

**Comment by dingo-d** [comment]
I can see the idea behind it, but since this is something development related, I don't think (or I sincerely hope) that people reading this code know what it's used for 😬

**Comment by szepeviktor** [comment]
> I don't think (or I sincerely hope) that people reading this code know what it's used for 😬

You do.

Mental programming!

**Pull request closed without merging**
