### PR TITLE
Say "API" and add badge links in README

### PR DESCRIPTION
**Pull request by szepeviktor**
TWO in one.

### CODE REVIEW

**Review by dingo-d — APPROVED** [review]

**Comment by dingo-d** [comment]
Can you just rebase the develop branch? Thanks!

**Comment by szepeviktor** [comment]
kép

**Comment by dingo-d** [comment]
> kép 👀

It's the duty of the one who opened PR to keep it up to date, not the maintainer 😉

**Comment by szepeviktor** [comment]
dity-duty 😆

**Pull request merged**
